const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const {createHash} = require('node:crypto');
const {execFileSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const pkg = require('../package.json');
const destination = path.join(root, 'build/release');
fs.mkdirSync(destination, {recursive: true});
execFileSync('npm', ['run', 'build'], {cwd: root, stdio: 'inherit'});
const [manifest] = JSON.parse(execFileSync('npm', ['pack', '--json', '--ignore-scripts', '--pack-destination', destination], {cwd: root, encoding: 'utf8'}));
assert.equal(manifest.name, pkg.name);
assert.equal(manifest.version, pkg.version);
assert.equal(pkg.license, 'MIT');
const files = new Set(manifest.files.map(file => file.path));
for (const file of ['LICENSE', 'README.md', 'CHANGELOG.md', 'package.json', 'lib/index.js', 'lib/index.d.ts', 'src/specs/NativeNearbyInteraction.ts', 'ios/NIController.swift', 'ios/BLEChannel.swift', 'ios/RNNearbyInteraction.h', 'ios/RNNearbyInteraction.mm', 'NearbyInteractionKit.podspec', 'react-native.config.js', 'app.plugin.js', 'plugin/index.js']) assert.ok(files.has(file), `Missing ${file}`);
for (const file of files) assert.ok(/^(LICENSE|README\.md|CHANGELOG\.md|CONTRIBUTING\.md|SECURITY\.md|package\.json|NearbyInteractionKit\.podspec|react-native\.config\.js|app\.plugin\.js|(?:src|lib|ios|plugin|docs)\/)/.test(file), `Unexpected distributed file: ${file}`);
const archive = path.join(destination, manifest.filename);
const sha256 = createHash('sha256').update(fs.readFileSync(archive)).digest('hex');
fs.writeFileSync(path.join(destination, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
fs.writeFileSync(path.join(destination, 'SHA256SUMS'), `${sha256}  ${manifest.filename}\n`);
console.log(`Verified ${manifest.filename}: ${files.size} files, ${manifest.size} bytes`);
